"""empty message

Revision ID: 157a977b29ce
Revises: 6c27e7844be3
Create Date: 2024-10-03 17:54:06.193181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157a977b29ce'
down_revision = '6c27e7844be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=300), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
